target("httpserver")
    set_kind("binary")
    set_default(false)
    add_files("httpserver.cpp")
    add_defines("ILIAS_ENABLE_LOG")
target_end()

target("console_echo")
    set_kind("binary")
    set_default(false)
    add_files("console_echo.cpp")
    add_defines("ILIAS_ENABLE_LOG")
target_end()