name: CI for windows by xmake with clang-cl

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    name: Build standard
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
      # The version to use. Should be a semver range or 'latest'. Or use branch@{branch_name} to select a branch.
        xmake-version: latest
    - name: Configure
      run: xmake f -m debug --toolchain=clang-cl -y
    - name: Build
      run: xmake -y
    - name: Run Test
      run: xmake test -v